### ISSUE TITLE
Produce indented output for requirements.txt

### ISSUE THREAD

**Issue by techtonik** [naiquevin/pipdeptree#31]
Would be cool if pipdeptree could produce indented output suitable for `requirements.txt`, like this one:
```
aspen==0.37
   filesystem_tree==1.0.1
   first==2.0.1
mimeparse==0.1.3
```
https://github.com/pypa/pip/issues/2918

**Comment by naiquevin** [comment]
If I understand it correctly, you mean to say that `pipdeptree` produces an alternate output that is indented like the one you've shown so that it can also be read by `pip -r` (I am not sure if `pip` ignores the indentations when reading the requirements file but let's assume it does). I think that's a brilliant idea! Although need to confirm the behaviour of `pip` when there are conflicting deps listed in the requirements file.

`pipdeptree` already _kind of_ supports this functionality with the `-f` flag, eg

```
$ pipdeptree -f
```

But you may notice that the output contains hyphens for bullets for the child dependencies. This can be removed but I am not sure how big a change it will be. I'll try spending some time on it. In the meanwhile, pull requests are welcome :-)

**Comment by techtonik** [comment]
> so that it can also be read by `pip -r`

Yes.

> I am not sure if pip ignores the indentations when reading the requirements file

It does. I tested. =)

> Although need to confirm the behaviour of pip when there are conflicting deps listed in the requirements file.

Why would anyone want a requirement file with conflicting requirements? For me the base case here is to fail with error.

> But you may notice that the output contains hyphens as bullets for the child dependencies.

Yes. I haven't tested if pip can eat bullets, but I suppose it can't.

As for pull requests. I actually filled it against `pip`, so if the code is ready, I may try to see what it takes to get it there. =)

**Comment by naiquevin** [comment]
> Why would anyone want a requirement file with conflicting requirements? For me the base case here is to fail with error.

If you use `pipdeptree` to update the requirements file (and suppose the hyphens are removed), then it may end up having more than 1 line for a dep with conflicting versions in case there are two pkgs that depend on different versions of it.

**Comment by techtonik** [comment]
Interesting if `pip` fails on `requirements.txt` with conflicting versions. For me it should.

**Comment by techtonik** [comment]
:+1:
