### ISSUE TITLE
Support using with both Python2 and Python3 installed

### ISSUE THREAD

**Issue by oryband** [naiquevin/pipdeptree#50]
I would like to execute pipdeptree on both my Python 2 and Python 3 installations. Currently this is not possible, since the script installed into `/usr/bin/pipdeptree` is "bound" to a specific python version using the `#!` hashbang at the top:

``` python
#!/usr/bin/python2

# -*- coding: utf-8 -*-
import re
import sys

from pipdeptree import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

I guess we can solve this by two ways:
1. Rename the installed script to `pipdeptree2` if it's installed using Python 2, and `ln -s` to `pipdeptree`. For Python 3 we'll have `pipdeptree3`. This will allow the user to keep the two versions.
2. Put them somewhere else e.g. in the Python system directory tree and link them to `/usr/bin/`, so the user can soft link/alias the scripts as he wishes.
3. Any other idea?

**Comment by naiquevin** [comment]
Writing and installing this executable is entirely handled by [setuptools entry points](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points) so I am not sure if it can controlled by package authors in any way.

It looks like the same python that is used by pip to install the package is added in the hashbang of the entry point scripts for that package. On my machine the hashbang in `pipdeptree` is`#!/usr/bin/python`. Can you check if the hashbang `pip` executable is`#!/usr/bin/python2` on your machine?

**Comment by oryband** [comment]
@naiquevin I'm using Arch Linux so `python2` points to Python 2.7 and `python` points to Python 3. In any case, do you have any idea how can I have two "versions" of pipdeptree installed, each one using a different python environment?

**Comment by naiquevin** [comment]
I have only tested pipdeptree on systems where `python` points to 2.7 and `python3` points to 3.x. Which python is used when you run `pip install`? Because I am assuming that must be deciding the path to python exec to put in the hashbang. 

Personally I follow a virtualenv based workflow to switch between different version of python, so I just need to install pipdeptree in the respective virtualenv.

**Comment by oryband** [comment]
@naiquevin on Arch `pip` calls `python3`'s `pip, and `pip2` calls `python2`'s

I have some globally installed packages that for system-wide use (like docker compose). That's why I'm asking this.

**Comment by maxrothman** [comment]
You can work around this issue by using `python2 -m pipdeptree` (or `python3`). If you really want separate executables and correct symlinks, there is a solution, but it's a bit hairy.

Since you can run arbitrary code in `setup.py` you could switch the entry point to name the script `pipdeptree2` or `pipdeptree3` depending on the version of python and drop in the symlink in the same directory `setup()` put the executable. There's some subtelty since `os.symlink` doesn't support Windows in Python2, but one could work around that by shelling out and calling `mlink`.

I'm happy to make a pull request if that's the direction you want to go.

**Comment by oryband** [comment]
I've eventually used the following solution to call `pipdeptree` on python3 or python2 packages:
```bash
$ python $HOME/.local/bin/pipdeptree  # ~/.local/bin is the location where pipdeptree is installed in my case
$ python2 $HOME/.local/bin/pipdeptree
```

**Comment by maxrothman** [comment]
I'm not sure that's really a viable solution. Users should not have to know where the pipdeptree executable is to use with python2/3 separately. The `python -m pipdeptree` solution is arguably better, since the module can be put wherever the user's `PYTHONPATH` is.

FWIW my offer of a PR still stands.

**Comment by naiquevin** [comment]
FYI: There is an open PR - https://github.com/naiquevin/pipdeptree/pull/76 that addresses the same issue with a different approach

**Comment by maxrothman** [comment]
While that PR is great and absolutely necessary, it doesn't solve the use-case of using pipdeptree for system-installed python packages with both Python 2 and 3.

**Comment by naiquevin** [comment]
I may be missing a lot of context here due to my zero experience of using system installed python 2 and 3 together on the same machine. I have used separate virtualenvs built using python 2/3 though, hence my understanding is based on that. To avoid having to create that setup and verify, let me explain the approach I am thinking and why I feel PR #76 is related to this.

If the packages installed for system wide python 2 and 3 are isolated (is there a pip2 and pip3 for the respective versions?), then it's _equivalent_ of having 2 different virtualenvs using python 2 and 3 respectively. Actually they wouldn't be virtualenvs here but all that PR #76 does is resolving the correct path for the python executable and then running pipdeptree script with that python executable. If that PR gets accepted, with little changes (eg. explicitly specifying the python exec path as part of command line options), it should be possible to run pipdeptree for the desired python executable.

**Comment by maxrothman** [comment]
You're correct that the work in #76 is necessary for working with multiple Pythons, but it's not quite sufficient. A typical system with both Python 2 and 3 installed at a system level looks like this:

```
/usr/bin/python: symlink to /usr/bin/python2
/usr/bin/python2: symlink to /usr/bin/python2.7
/usr/bin/python3: symlink to /usr/bin/python3.6
/usr/bin/python2.7: executable
/usr/bin/python3.6: executable
```

Which python is the default depends on the version that the `/usr/bin/python` symlink points to. The problem with pipdeptree only using the default python is then there's no way to specify a different python to use. The way most programs (e.g. pip) work around this is by mirroring this symlink pattern (e.g. `/usr/bin/pipdeptree2` and `/usr/bin/pipdeptree3` are executables, and `/usr/bin/pipdeptree` is a symlink to one of them). To figure out which version should be pointed to by the default pipdeptree executable, you could figure out which version of python is the default, or even take the lazy approach and just have it use the version of python used to install pipdeptree.

**Comment by oryband** [comment]
> The python -m pipdeptree solution is arguably better

Yeah I agree, more elegant.
