### ISSUE TITLE
pip refactoring will break pipdeptree

### ISSUE THREAD

**Issue by ghost** [naiquevin/pipdeptree#83]
@dstufft has decided to move around the imports in pypa/pip#4700, which will necessitate adjustments to the imports in pip 10.0.

**Comment by naiquevin** [comment]
Yeah, `pipdeptree` is pretty much a hack because it relies on pip as a library and uses it's internal api. I knew we'd run into this situation some day! But if it's just code being moved around, I think it should be a fairly straightforward change to handle imports for different versions of pip using a simple try..catch block. 

Thanks for informing 👍  I'll keep track of that PR in the pip repo.

**Comment by dstufft** [comment]
Yea, basically no code changes, just shuffling everything into ``pip._internal`` to try and make it more obvious that the APIs are internal, to hopefully prevent some people from accidentally using them unawares of that fact.
